Repository eigenwallet/core, pull requests merged in 2025-05, with the labels that each got.

#287 feat(gui): Add a Introduction for new users
  CHANGELOG.md
  src-gui/src/assets/currencyFetching.svg
  src-gui/src/assets/groupWithChatbubbles.png
  src-gui/src/assets/mockConfigureSwap.svg
  src-gui/src/assets/mockHistoryPage.svg
  src-gui/src/assets/mockMakerSelection.svg
  src-gui/src/assets/simpleSwapFlowDiagram.svg
  src-gui/src/assets/walletWithBitcoinAndMonero.png
  src-gui/src/renderer/components/App.tsx
  src-gui/src/renderer/components/inputs/CardSelection/CardSelectionContext.tsx
  src-gui/src/renderer/components/inputs/CardSelection/CardSelectionGroup.tsx
  src-gui/src/renderer/components/inputs/CardSelection/CardSelectionOption.tsx
  src-gui/src/renderer/components/modal/introduction/IntroductionModal.tsx
  src-gui/src/renderer/components/modal/introduction/slides/Slide01_GettingStarted.tsx
  src-gui/src/renderer/components/modal/introduction/slides/Slide02_ChooseAMaker.tsx
  src-gui/src/renderer/components/modal/introduction/slides/Slide03_PrepareSwap.tsx
  src-gui/src/renderer/components/modal/introduction/slides/Slide04_ExecuteSwap.tsx
  src-gui/src/renderer/components/modal/introduction/slides/Slide05_KeepAnEyeOnYourSwaps.tsx
  src-gui/src/renderer/components/modal/introduction/slides/Slide06_FiatPricePreference.tsx
  src-gui/src/renderer/components/modal/introduction/slides/Slide07_ReachOut.tsx
  src-gui/src/renderer/components/modal/introduction/slides/SlideTemplate.tsx
  src-gui/src/renderer/components/modal/introduction/slides/SlideTypes.ts
  src-gui/src/renderer/components/navigation/NavigationFooter.tsx
  src-gui/src/renderer/components/other/ExternalLink.tsx
  src-gui/src/store/features/settingsSlice.ts
Labels: P3

#333 fix(swap): Add retry logic for Bitcoin wallet sync
  CHANGELOG.md
  swap/src/bitcoin/wallet.rs
Labels: codex

#337 Add AGENT overview
  AGENT.md
Labels: codex

#341 Update docs for external bitcoin address
  AGENT.md
  CHANGELOG.md
  dev-docs/asb/README.md
  docs/pages/becoming_a_maker/overview.mdx
Labels: codex

#346 refactor(cli): Remove obsolete RPC server
  .github/workflows/ci.yml
  CHANGELOG.md
  Cargo.lock
  swap/Cargo.toml
  swap/src/cli/api/request.rs
  swap/src/cli/command.rs
  swap/src/lib.rs
  swap/src/rpc.rs
  swap/src/rpc/methods.rs
  swap/tests/rpc.rs
Labels: codex

#350 docs: add PR title examples
  AGENT.md
Labels: codex

#349 Update Bitcoin fee limit
  swap/src/bitcoin/wallet.rs
Labels: codex

#348 Handle missing Monero node
  justfile
  monero-sys/cpp/bridge.h
  swap/src/cli/api.rs
  swap/src/cli/api/tauri_bindings.rs
  swap/src/cli/command.rs
  swap/src/monero/wallet_rpc.rs
Labels: codex

#359 fix(gui): update feedback GitHub issue link
  src-gui/src/renderer/components/pages/help/ContactInfoBox.tsx
Labels: codex

#331 feat(gui): Feedback quick fixes
  Cargo.lock
  docs/components/Logo.tsx
  docs/pages/_meta.json
  docs/pages/send_feedback.mdx
  docs/public/android-chrome-192x192.png
  docs/public/android-chrome-512x512.png
  docs/public/apple-touch-icon.png
  docs/public/favicon.ico
  docs/public/feedback_button_modal.png
  docs/public/icon.svg
  docs/public/manifest.webmanifest
  docs/theme.config.jsx
  src-gui/src/renderer/components/modal/feedback/FeedbackDialog.tsx
  src-gui/src/renderer/components/modal/feedback/LogViewer.tsx
  src-gui/src/renderer/components/modal/feedback/SwapSelectDropDown.tsx
  src-gui/src/renderer/components/modal/feedback/useFeedback.ts
  src-gui/src/renderer/components/pages/history/table/ExportLogsButton.tsx
  src-gui/src/renderer/components/pages/history/table/HistoryRowExpanded.tsx
  src-gui/src/renderer/rpc.ts
  src-tauri/Cargo.toml
  src-tauri/src/lib.rs
Labels: P2

#366 feat(asb): add trace flag for stdout
  src-gui/src/renderer/components/pages/help/DaemonControlBox.tsx
  swap/src/asb/command.rs
  swap/src/bin/asb.rs
  swap/src/cli/api.rs
  swap/src/common/tracing_util.rs
Labels: codex
